name: release-jobs
permissions: 
  contents: write

on:
  workflow_dispatch:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  test-and-tag-release:
    runs-on: ubuntu-22.04
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v3
      with:
        go-version: '^1.20.0'

    - name: Update PATH variable
      run: echo "$HOME/go/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y gnome-keyring openssh-client
        pip install keyring sagecipher
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        eval "$(ssh-agent -s)"
        ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""
        ssh-add ~/.ssh/id_rsa


    - name: Run tests
      run: make test

    - name: Get version
      run: echo VERSION=$(cat ./VERSION) >> $GITHUB_ENV

    - name: Check if tag exists in master
      run: |
        if git rev-parse ${{ env.VERSION }} > /dev/null 2>&1
        then
          echo "Version ${{ env.VERSION}} already exists"
          echo "TAG_EXISTS=1" >> $GITHUB_ENV
        else
          echo "Version ${{ env.VERSION}} does not exist"
          echo "TAG_EXISTS=0" >> $GITHUB_ENV
        fi

    - name: Generate release
      if: ${{ (github.ref == 'refs/heads/master') && (env.TAG_EXISTS == 0) }}
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VERSION }}
        generate_release_notes: false